name: CI-Frontend

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install modules
        run: |
          cd frontend
          yarn
      - name: Run ESLint
        run: |
          cd frontend
          yarn eslint . --fix
